version: "3"
services:
  api-database:
    image: mongo:4.0
    container_name: "voting-database"
    ports:
      - 27017:27017
#    volumes:
#      - "/tmp/mongo:/data/db"
  api:
    image: voting-api:0.0.1
    ports:
      - 8080:8080
    links:
      - api-database
